/**
 * Script untuk otomatis mendeteksi IP lokal dan mengupdate .env
 * Jalankan: node scripts/update-env-ip.js
 * Atau otomatis via npm scripts (lihat package.json)
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

// Port untuk setiap microservice
const PORTS = {
  AUTH:   3010,
  MASTER: 3020,
  HR:     3030,
  MOBILE: 3040,
};

/**
 * Mendapatkan IP lokal yang aktif (bukan loopback/virtual)
 * Prioritas: WiFi/Ethernet aktif, bukan 127.x atau virtual adapter
 */
function getLocalIP() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [name, nets] of Object.entries(interfaces)) {
    if (!nets) continue;
    for (const net of nets) {
      // Hanya IPv4, bukan loopback, dan bukan internal
      if (net.family === 'IPv4' && !net.internal) {
        // Skip virtual adapters (VirtualBox, VMware, Docker, dll)
        const lowerName = name.toLowerCase();
        if (
          lowerName.includes('vmware') ||
          lowerName.includes('virtualbox') ||
          lowerName.includes('vethernet') ||
          lowerName.includes('docker') ||
          lowerName.includes('wsl') ||
          lowerName.includes('loopback')
        ) {
          continue;
        }
        candidates.push({ name, address: net.address });
      }
    }
  }

  if (candidates.length === 0) {
    console.warn('No local IP found, using localhost');
    return 'localhost';
  }

  const selected = candidates[0];
  
  if (candidates.length > 1) {
    console.log('Multiple network interfaces found:');
    candidates.forEach((c, i) => {
      console.log('  ' + (i === 0 ? '[SELECTED] ' : '           ') + '[' + c.name + '] ' + c.address);
    });
  }

  return selected.address;
}

function updateEnvFile(ip) {
  const envPath = path.join(__dirname, '..', '.env');
  
  const content = '# Microservices Backend Base URLs\n' +
    '# Auto-generated by scripts/update-env-ip.js pada ' + new Date().toLocaleString('id-ID') + '\n' +
    'EXPO_PUBLIC_AUTH_API_URL=http://' + ip + ':' + PORTS.AUTH + '/api/v1\n' +
    'EXPO_PUBLIC_MASTER_API_URL=http://' + ip + ':' + PORTS.MASTER + '/api/v1/master\n' +
    'EXPO_PUBLIC_HR_API_URL=http://' + ip + ':' + PORTS.HR + '/api/v1/hr\n' +
    'EXPO_PUBLIC_MOBILE_API_URL=http://' + ip + ':' + PORTS.MOBILE + '/api/v1/mobile\n' +
    '\n' +
    '# Default API URL\n' +
    'EXPO_PUBLIC_API_URL=http://' + ip + ':' + PORTS.AUTH + '/api/v1\n';

  fs.writeFileSync(envPath, content, 'utf8');
  return content;
}

const ip = getLocalIP();
console.log('IP lokal terdeteksi: ' + ip);
const envContent = updateEnvFile(ip);
console.log('.env berhasil diupdate:');
console.log(envContent);
